'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '../contexts/AuthContext';
import MultipleImageUpload from '../components/MultipleImageUpload';
import LocationPicker from '../components/LocationPicker';
import { Button } from '../components/Button';
import AuthModal from '../components/AuthModal';
import { savePet, Pet } from '../utils/storage';
import { ChevronLeftIcon, CheckCircleIcon } from '@heroicons/react/24/outline';
import toast from 'react-hot-toast';

const FORM_STORAGE_KEY = 'pawAlert_draftReport';

export default function ReportMissingPet() {
    const router = useRouter();
    const { user, loading: authLoading } = useAuth();
    const [step, setStep] = useState(1);
    const [isLoading, setIsLoading] = useState(false);
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [showAuthModal, setShowAuthModal] = useState(false);

    const [formData, setFormData] = useState<Partial<Pet>>({
        status: 'lost',
        sightings: [],
        photos: [],
        rewardCurrency: 'USD',
        createdAt: new Date().toISOString(),
    });

    // Load saved draft from localStorage on mount
    useEffect(() => {
        const savedDraft = localStorage.getItem(FORM_STORAGE_KEY);
        if (savedDraft) {
            try {
                const parsedDraft = JSON.parse(savedDraft);
                setFormData(parsedDraft);
                toast.success('Borrador restaurado');
            } catch (error) {
                console.error('Error parsing saved draft:', error);
                localStorage.removeItem(FORM_STORAGE_KEY);
            }
        }
    }, []);

    // Save draft to localStorage whenever formData changes
    useEffect(() => {
        // Only save if there's actual data beyond the initial state
        if (formData.name || formData.photo || formData.breed) {
            localStorage.setItem(FORM_STORAGE_KEY, JSON.stringify(formData));
        }
    }, [formData]);

    const handleImagesChange = (images: string[]) => {
        setFormData({ 
            ...formData, 
            photos: images,
            photo: images[0] || '' // Primary photo is the first one
        });
    };

    const handleLocationSelect = (location: { lat: number; lng: number; address: string }) => {
        setFormData({ ...formData, lastSeenLocation: location });
    };

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
        const { name, value } = e.target;
        // Convert date string to ISO format for lastSeenDate
        if (name === 'lastSeenDate' && value) {
            const date = new Date(value);
            setFormData({ ...formData, [name]: date.toISOString() });
        } else {
            setFormData({ ...formData, [name]: value });
        }
    };

    const nextStep = () => {
        // Check authentication before allowing to proceed
        if (!user) {
            setShowAuthModal(true);
            return;
        }
        setStep(step + 1);
    };

    const prevStep = () => setStep(step - 1);

    const clearDraft = () => {
        localStorage.removeItem(FORM_STORAGE_KEY);
        setFormData({
            status: 'lost',
            sightings: [],
            createdAt: new Date().toISOString(),
        });
        setStep(1);
        toast.success('Borrador eliminado');
    };

    const handleSubmit = async () => {
        if (isSubmitting) return;

        if (!user) {
            setShowAuthModal(true);
            return;
        }

        setIsSubmitting(true);
        setIsLoading(true);
        try {
            // Remove id from formData as it's generated by Firestore
            const { id, ...petData } = formData as Pet;

            const newPetId = await savePet({
                ...petData,
                userId: user.uid,
                contactName: user.displayName || formData.contactName || '',
                lastSeenDate: formData.lastSeenDate || new Date().toISOString(),
            });

            // Clear localStorage draft after successful submission
            localStorage.removeItem(FORM_STORAGE_KEY);

            toast.success('¡Reporte publicado exitosamente!');
            router.push(`/pet/${newPetId}`);
        } catch (error) {
            console.error('Error saving pet:', error);
            toast.error('Hubo un error al guardar el reporte. Por favor intenta de nuevo.');
            setIsSubmitting(false);
        } finally {
            setIsLoading(false);
        }
    };

    // Show loading while checking authentication
    if (authLoading) {
        return (
            <div className="min-h-screen flex items-center justify-center">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600"></div>
            </div>
        );
    }

    return (
        <>
            <AuthModal
                isOpen={showAuthModal}
                onClose={() => setShowAuthModal(false)}
                onSuccess={() => setShowAuthModal(false)}
            />
        <main className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
            <div className="max-w-2xl mx-auto">
                {/* Progress Steps */}
                <nav aria-label="Progress" className="mb-12">
                    <ol role="list" className="flex items-center">
                        {[1, 2, 3, 4].map((s, stepIdx) => (
                            <li key={s} className={`relative ${stepIdx !== 3 ? 'pr-8 sm:pr-20' : ''}`}>
                                {s < step ? (
                                    <div className="absolute inset-0 flex items-center" aria-hidden="true">
                                        <div className="h-0.5 w-full bg-primary-600" />
                                    </div>
                                ) : null}
                                <div className={`relative flex h-8 w-8 items-center justify-center rounded-full ${s <= step ? 'bg-primary-600 hover:bg-primary-900' : 'bg-gray-200'
                                    }`}>
                                    {s < step ? (
                                        <CheckCircleIcon className="h-5 w-5 text-white" aria-hidden="true" />
                                    ) : (
                                        <span className={`text-sm font-medium ${s === step ? 'text-white' : 'text-gray-500'}`}>
                                            {s}
                                        </span>
                                    )}
                                </div>
                            </li>
                        ))}
                    </ol>
                </nav>

                <div className="bg-white shadow-xl rounded-2xl overflow-hidden">
                    <div className="px-8 py-10">
                        {step === 1 && (
                            <div className="space-y-6">
                                <div className="text-center">
                                    <h2 className="text-2xl font-bold text-gray-900">Información Básica</h2>
                                    <p className="mt-2 text-gray-500">Comenzamos con fotos y la fecha en que se perdió tu mascota.</p>
                                </div>
                                <MultipleImageUpload 
                                    images={formData.photos || []} 
                                    onImagesChange={handleImagesChange}
                                    maxImages={5}
                                    label="Fotos de la mascota (máximo 5)"
                                />

                                <div>
                                    <label htmlFor="lastSeenDate" className="block text-sm font-medium text-gray-700 mb-2">
                                        ¿Cuándo se perdió tu mascota?
                                    </label>
                                    <input
                                        type="date"
                                        name="lastSeenDate"
                                        id="lastSeenDate"
                                        required
                                        max={new Date().toISOString().split('T')[0]}
                                        className="block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm border p-2"
                                        value={formData.lastSeenDate ? new Date(formData.lastSeenDate).toISOString().split('T')[0] : ''}
                                        onChange={handleInputChange}
                                    />
                                    <p className="mt-1 text-xs text-gray-500">Esta información ayuda a la comunidad a saber qué tan reciente es el caso</p>
                                </div>

                                <div className="flex justify-end pt-6">
                                    <Button onClick={nextStep} disabled={!formData.photos || formData.photos.length === 0 || !formData.lastSeenDate}>Siguiente: Detalles</Button>
                                </div>
                            </div>
                        )}

                        {step === 2 && (
                            <div className="space-y-6">
                                <div className="text-center">
                                    <h2 className="text-2xl font-bold text-gray-900">Detalles de la Mascota</h2>
                                    <p className="mt-2 text-gray-500">Cuéntanos sobre tu amigo perdido.</p>
                                </div>

                                <div className="grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
                                    <div className="sm:col-span-3">
                                        <label htmlFor="name" className="block text-sm font-medium text-gray-700">Nombre</label>
                                        <input
                                            type="text"
                                            name="name"
                                            id="name"
                                            required
                                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm border p-2"
                                            value={formData.name || ''}
                                            onChange={handleInputChange}
                                        />
                                    </div>

                                    <div className="sm:col-span-3">
                                        <label htmlFor="type" className="block text-sm font-medium text-gray-700">Tipo</label>
                                        <select
                                            id="type"
                                            name="type"
                                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm border p-2"
                                            value={formData.type || 'dog'}
                                            onChange={handleInputChange}
                                        >
                                            <option value="dog">Perro</option>
                                            <option value="cat">Gato</option>
                                            <option value="other">Otro</option>
                                        </select>
                                    </div>

                                    <div className="sm:col-span-6">
                                        <label htmlFor="breed" className="block text-sm font-medium text-gray-700">Raza</label>
                                        <input
                                            type="text"
                                            name="breed"
                                            id="breed"
                                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm border p-2"
                                            value={formData.breed || ''}
                                            onChange={handleInputChange}
                                        />
                                    </div>

                                    <div className="sm:col-span-3">
                                        <label htmlFor="color" className="block text-sm font-medium text-gray-700">Color</label>
                                        <input
                                            type="text"
                                            name="color"
                                            id="color"
                                            required
                                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm border p-2"
                                            value={formData.color || ''}
                                            onChange={handleInputChange}
                                        />
                                    </div>

                                    <div className="sm:col-span-3">
                                        <label htmlFor="size" className="block text-sm font-medium text-gray-700">Tamaño</label>
                                        <select
                                            id="size"
                                            name="size"
                                            required
                                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm border p-2"
                                            value={formData.size || ''}
                                            onChange={handleInputChange}
                                        >
                                            <option value="">Selecciona un tamaño</option>
                                            <option value="Pequeño">Pequeño (0-10 kg)</option>
                                            <option value="Mediano">Mediano (10-25 kg)</option>
                                            <option value="Grande">Grande (25+ kg)</option>
                                        </select>
                                    </div>

                                    <div className="sm:col-span-6">
                                        <label htmlFor="description" className="block text-sm font-medium text-gray-700">Descripción</label>
                                        <textarea
                                            id="description"
                                            name="description"
                                            rows={3}
                                            required
                                            placeholder="Describe a tu mascota (comportamiento, personalidad, etc.)"
                                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm border p-2"
                                            value={formData.description || ''}
                                            onChange={handleInputChange}
                                        />
                                    </div>

                                    <div className="sm:col-span-6">
                                        <label htmlFor="distinguishingFeatures" className="block text-sm font-medium text-gray-700">Señas Particulares</label>
                                        <textarea
                                            id="distinguishingFeatures"
                                            name="distinguishingFeatures"
                                            rows={2}
                                            required
                                            placeholder="Cicatrices, manchas únicas, collar especial, etc."
                                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm border p-2"
                                            value={formData.distinguishingFeatures || ''}
                                            onChange={handleInputChange}
                                        />
                                    </div>
                                </div>

                                <div className="flex justify-between pt-6">
                                    <Button variant="ghost" onClick={prevStep}>Atrás</Button>
                                    <Button
                                        onClick={nextStep}
                                        disabled={!formData.name || !formData.breed || !formData.color || !formData.size || !formData.description || !formData.distinguishingFeatures}
                                    >
                                        Siguiente: Ubicación
                                    </Button>
                                </div>
                            </div>
                        )}

                        {step === 3 && (
                            <div className="space-y-6">
                                <div className="text-center">
                                    <h2 className="text-2xl font-bold text-gray-900">Última Ubicación Vista</h2>
                                    <p className="mt-2 text-gray-500">¿Dónde fue vista tu mascota por última vez?</p>
                                </div>

                                <LocationPicker onLocationSelect={handleLocationSelect} />

                                <div className="flex justify-between pt-6">
                                    <Button variant="ghost" onClick={prevStep}>Atrás</Button>
                                    <Button onClick={nextStep} disabled={!formData.lastSeenLocation}>Siguiente: Contacto</Button>
                                </div>
                            </div>
                        )}

                        {step === 4 && (
                            <div className="space-y-6">
                                <div className="text-center">
                                    <h2 className="text-2xl font-bold text-gray-900">Información de Contacto</h2>
                                    <p className="mt-2 text-gray-500">¿Cómo podemos contactarte?</p>
                                </div>

                                <div className="grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
                                    <div className="sm:col-span-3">
                                        <label htmlFor="contactName" className="block text-sm font-medium text-gray-700">Tu Nombre</label>
                                        <input
                                            type="text"
                                            name="contactName"
                                            id="contactName"
                                            required
                                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm border p-2"
                                            value={formData.contactName || ''}
                                            onChange={handleInputChange}
                                        />
                                    </div>

                                    <div className="sm:col-span-3">
                                        <label htmlFor="contactPhone" className="block text-sm font-medium text-gray-700">Teléfono</label>
                                        <input
                                            type="tel"
                                            name="contactPhone"
                                            id="contactPhone"
                                            required
                                            pattern="[0-9+\-\s()]{8,}"
                                            placeholder="+34 123 456 789"
                                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm border p-2"
                                            value={formData.contactPhone || ''}
                                            onChange={handleInputChange}
                                        />
                                    </div>

                                    <div className="sm:col-span-6">
                                        <label htmlFor="contactEmail" className="block text-sm font-medium text-gray-700">Email</label>
                                        <input
                                            type="email"
                                            name="contactEmail"
                                            id="contactEmail"
                                            required
                                            placeholder="tu@email.com"
                                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm border p-2"
                                            value={formData.contactEmail || ''}
                                            onChange={handleInputChange}
                                        />
                                    </div>

                                    <div className="sm:col-span-6">
                                        <label htmlFor="reward" className="block text-sm font-medium text-gray-700 mb-2">Recompensa (Opcional)</label>
                                        <div className="flex gap-3">
                                            <select
                                                name="rewardCurrency"
                                                id="rewardCurrency"
                                                className="block w-32 rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm border p-2"
                                                value={formData.rewardCurrency || 'USD'}
                                                onChange={handleInputChange}
                                            >
                                                <option value="USD">USD $</option>
                                                <option value="MXN">MXN $</option>
                                                <option value="EUR">EUR €</option>
                                                <option value="GBP">GBP £</option>
                                                <option value="COP">COP $</option>
                                                <option value="ARS">ARS $</option>
                                                <option value="CLP">CLP $</option>
                                            </select>
                                            <input
                                                type="text"
                                                name="reward"
                                                id="reward"
                                                className="flex-1 focus:ring-primary-500 focus:border-primary-500 block w-full sm:text-sm border-gray-300 rounded-md border p-2"
                                                placeholder="Ejemplo: 50,000 o 50.000"
                                                value={formData.reward || ''}
                                                onChange={handleInputChange}
                                            />
                                        </div>
                                        <p className="mt-1 text-xs text-gray-500">Usa comas o puntos como separador de miles según tu preferencia</p>
                                    </div>
                                </div>

                                <div className="flex justify-between pt-6">
                                    <Button variant="ghost" onClick={prevStep}>Atrás</Button>
                                    <Button
                                        onClick={handleSubmit}
                                        isLoading={isLoading || isSubmitting}
                                        disabled={!formData.contactName || !formData.contactPhone || !formData.contactEmail || isSubmitting}
                                    >
                                        Publicar Reporte
                                    </Button>
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </main>
        </>
    );
}
