'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import ImageUpload from '../components/ImageUpload';
import LocationPicker from '../components/LocationPicker';
import { Button } from '../components/Button';
import { savePet, Pet } from '../utils/storage';
import { ChevronLeftIcon, CheckCircleIcon } from '@heroicons/react/24/outline';

export default function ReportMissingPet() {
    const router = useRouter();
    const [step, setStep] = useState(1);
    const [isLoading, setIsLoading] = useState(false);
    const [isSubmitting, setIsSubmitting] = useState(false);

    const [formData, setFormData] = useState<Partial<Pet>>({
        status: 'lost',
        sightings: [],
        createdAt: new Date().toISOString(),
    });

    const handleImageSelect = (url: string | null) => {
        if (url) {
            setFormData({ ...formData, photo: url });
        } else {
            setFormData({ ...formData, photo: undefined });
        }
    };

    const handleLocationSelect = (location: { lat: number; lng: number; address: string }) => {
        setFormData({ ...formData, lastSeenLocation: location });
    };

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
        const { name, value } = e.target;
        setFormData({ ...formData, [name]: value });
    };

    const nextStep = () => setStep(step + 1);
    const prevStep = () => setStep(step - 1);

    const handleSubmit = async () => {
        if (isSubmitting) return;

        setIsSubmitting(true);
        setIsLoading(true);
        try {
            // Remove id from formData as it's generated by Firestore
            const { id, ...petData } = formData as Pet;

            const newPetId = await savePet({
                ...petData,
                lastSeenDate: new Date().toISOString(),
            });

            router.push(`/pet/${newPetId}`);
        } catch (error) {
            console.error('Error saving pet:', error);
            alert('Hubo un error al guardar el reporte. Por favor intenta de nuevo.');
            setIsSubmitting(false);
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <main className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
            <div className="max-w-2xl mx-auto">
                {/* Progress Steps */}
                <nav aria-label="Progress" className="mb-12">
                    <ol role="list" className="flex items-center">
                        {[1, 2, 3, 4].map((s, stepIdx) => (
                            <li key={s} className={`relative ${stepIdx !== 3 ? 'pr-8 sm:pr-20' : ''}`}>
                                {s < step ? (
                                    <div className="absolute inset-0 flex items-center" aria-hidden="true">
                                        <div className="h-0.5 w-full bg-primary-600" />
                                    </div>
                                ) : null}
                                <div className={`relative flex h-8 w-8 items-center justify-center rounded-full ${s <= step ? 'bg-primary-600 hover:bg-primary-900' : 'bg-gray-200'
                                    }`}>
                                    {s < step ? (
                                        <CheckCircleIcon className="h-5 w-5 text-white" aria-hidden="true" />
                                    ) : (
                                        <span className={`text-sm font-medium ${s === step ? 'text-white' : 'text-gray-500'}`}>
                                            {s}
                                        </span>
                                    )}
                                </div>
                            </li>
                        ))}
                    </ol>
                </nav>

                <div className="bg-white shadow-xl rounded-2xl overflow-hidden">
                    <div className="px-8 py-10">
                        {step === 1 && (
                            <div className="space-y-6">
                                <div className="text-center">
                                    <h2 className="text-2xl font-bold text-gray-900">Sube una Foto</h2>
                                    <p className="mt-2 text-gray-500">Una foto clara ayuda a tus vecinos a identificar a tu mascota rápidamente.</p>
                                </div>
                                <ImageUpload onImageSelect={handleImageSelect} initialImage={formData.photo} />
                                <div className="flex justify-end pt-6">
                                    <Button onClick={nextStep} disabled={!formData.photo}>Siguiente: Detalles</Button>
                                </div>
                            </div>
                        )}

                        {step === 2 && (
                            <div className="space-y-6">
                                <div className="text-center">
                                    <h2 className="text-2xl font-bold text-gray-900">Detalles de la Mascota</h2>
                                    <p className="mt-2 text-gray-500">Cuéntanos sobre tu amigo perdido.</p>
                                </div>

                                <div className="grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
                                    <div className="sm:col-span-3">
                                        <label htmlFor="name" className="block text-sm font-medium text-gray-700">Nombre</label>
                                        <input
                                            type="text"
                                            name="name"
                                            id="name"
                                            required
                                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm border p-2"
                                            value={formData.name || ''}
                                            onChange={handleInputChange}
                                        />
                                    </div>

                                    <div className="sm:col-span-3">
                                        <label htmlFor="type" className="block text-sm font-medium text-gray-700">Tipo</label>
                                        <select
                                            id="type"
                                            name="type"
                                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm border p-2"
                                            value={formData.type || 'dog'}
                                            onChange={handleInputChange}
                                        >
                                            <option value="dog">Perro</option>
                                            <option value="cat">Gato</option>
                                            <option value="other">Otro</option>
                                        </select>
                                    </div>

                                    <div className="sm:col-span-6">
                                        <label htmlFor="breed" className="block text-sm font-medium text-gray-700">Raza</label>
                                        <input
                                            type="text"
                                            name="breed"
                                            id="breed"
                                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm border p-2"
                                            value={formData.breed || ''}
                                            onChange={handleInputChange}
                                        />
                                    </div>

                                    <div className="sm:col-span-6">
                                        <label htmlFor="color" className="block text-sm font-medium text-gray-700">Color</label>
                                        <input
                                            type="text"
                                            name="color"
                                            id="color"
                                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm border p-2"
                                            value={formData.color || ''}
                                            onChange={handleInputChange}
                                        />
                                    </div>

                                    <div className="sm:col-span-6">
                                        <label htmlFor="description" className="block text-sm font-medium text-gray-700">Descripción</label>
                                        <textarea
                                            id="description"
                                            name="description"
                                            rows={3}
                                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm border p-2"
                                            value={formData.description || ''}
                                            onChange={handleInputChange}
                                        />
                                    </div>
                                </div>

                                <div className="flex justify-between pt-6">
                                    <Button variant="ghost" onClick={prevStep}>Atrás</Button>
                                    <Button onClick={nextStep} disabled={!formData.name}>Siguiente: Ubicación</Button>
                                </div>
                            </div>
                        )}

                        {step === 3 && (
                            <div className="space-y-6">
                                <div className="text-center">
                                    <h2 className="text-2xl font-bold text-gray-900">Última Ubicación Vista</h2>
                                    <p className="mt-2 text-gray-500">¿Dónde fue vista tu mascota por última vez?</p>
                                </div>

                                <LocationPicker onLocationSelect={handleLocationSelect} />

                                <div className="flex justify-between pt-6">
                                    <Button variant="ghost" onClick={prevStep}>Atrás</Button>
                                    <Button onClick={nextStep} disabled={!formData.lastSeenLocation}>Siguiente: Contacto</Button>
                                </div>
                            </div>
                        )}

                        {step === 4 && (
                            <div className="space-y-6">
                                <div className="text-center">
                                    <h2 className="text-2xl font-bold text-gray-900">Información de Contacto</h2>
                                    <p className="mt-2 text-gray-500">¿Cómo podemos contactarte?</p>
                                </div>

                                <div className="grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
                                    <div className="sm:col-span-3">
                                        <label htmlFor="contactName" className="block text-sm font-medium text-gray-700">Tu Nombre</label>
                                        <input
                                            type="text"
                                            name="contactName"
                                            id="contactName"
                                            required
                                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm border p-2"
                                            value={formData.contactName || ''}
                                            onChange={handleInputChange}
                                        />
                                    </div>

                                    <div className="sm:col-span-3">
                                        <label htmlFor="contactPhone" className="block text-sm font-medium text-gray-700">Teléfono</label>
                                        <input
                                            type="tel"
                                            name="contactPhone"
                                            id="contactPhone"
                                            required
                                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm border p-2"
                                            value={formData.contactPhone || ''}
                                            onChange={handleInputChange}
                                        />
                                    </div>

                                    <div className="sm:col-span-6">
                                        <label htmlFor="reward" className="block text-sm font-medium text-gray-700">Recompensa (Opcional)</label>
                                        <div className="mt-1 relative rounded-md shadow-sm">
                                            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                                <span className="text-gray-500 sm:text-sm">$</span>
                                            </div>
                                            <input
                                                type="text"
                                                name="reward"
                                                id="reward"
                                                className="focus:ring-primary-500 focus:border-primary-500 block w-full pl-7 pr-12 sm:text-sm border-gray-300 rounded-md border p-2"
                                                placeholder="0.00"
                                                value={formData.reward || ''}
                                                onChange={handleInputChange}
                                            />
                                        </div>
                                    </div>
                                </div>

                                <div className="flex justify-between pt-6">
                                    <Button variant="ghost" onClick={prevStep}>Atrás</Button>
                                    <Button onClick={handleSubmit} isLoading={isLoading || isSubmitting} disabled={!formData.contactName || !formData.contactPhone || isSubmitting}>
                                        Publicar Reporte
                                    </Button>
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </main>
    );
}
